app/services/nrel_service.rb, spec/services/nrel_service_spec.rb
Add NrelService that hits the index and summaries endpoints for the Open PV installs api. Includes tests with and without params.
@julsfelic 
closes #1
=> Set up nrel service

Gemfile, Gemfile.lock
Made the first deployment to heroku
Closes #5
=> Deploy to heroku

config/database.yml, coverage/.resultset.json, coverage/index.html
Went through the steps to run the app locally in production for
debugging purposes
Closes #9
=> Setup app to run locally on production

Gemfile, app/models/state.rb, app/models/summary.rb, db/migrate/20160419233223_create_states.rb, db/migrate/20160419233439_create_summaries.rb, db/schema.rb, lib/tasks/add_nrel_api_data_to_database.rake, spec/factories.rb, spec/models/state_spec.rb, spec/models/summary_spec.rb
Create rake seed task to seed database from NREL API. Adds PV data for all 50 states and for the US for years from 2007-1016 and the total for all years. 
closes #13
=> Set up rake task

Gemfile, Gemfile.lock, Rakefile, coverage/.resultset.json, coverage/index.html
=> Add delayed_task gem

app/models/state.rb, app/models/summary.rb, spec/models/state_spec.rb, spec/models/summary_spec.rb
Add validations for state model
closes #23
=> Add state and summary validations and tests

.gitignore, Gemfile, Gemfile.lock, app/controllers/api/v1/summaries/summaries_controller.rb, app/controllers/api_controller.rb, app/models/state.rb, config/routes.rb, coverage/.resultset.json, coverage/index.html, spec/requests/api/v1/summaries_spec.rb, spec/support/factory_girl.rb
Add SummariesController with an index action to find data by state or total for the US
closes #25
=> Add endpoint for finding US and state summaries by year.

app/assets/javascripts/cost_by_year_chart.js, app/assets/javascripts/installs_chart.js, app/assets/javascripts/size_chart.js, app/assets/javascripts/state_loader.js, app/assets/javascripts/usa_loader.js, app/controllers/api/v1/summaries/summaries_controller.rb, app/controllers/states_controller.rb, app/models/state.rb, app/views/layouts/_nav.html.erb, app/views/layouts/application.html.erb, app/views/shared/_graphs.html.erb, app/views/states/index.html.erb, app/views/states/show.html.erb, config/routes.rb, spec/features/user_can_view_navbar_spec.rb
Added the necessary JS to hit our end point and update the chart.js
charts on the page
closes #11
=> Add AJAX calls to update the graphs for US and state

app/assets/javascripts/state_loader.js, app/assets/javascripts/usa_loader.js, coverage/.resultset.json, coverage/index.html
=> Change JSON to use heroku address

app/assets/stylesheets/main.scss, app/views/layouts/application.html.erb, app/views/shared/_callout_boxes.html.erb, app/views/states/index.html.erb, app/views/states/show.html.erb, coverage/.resultset.json, coverage/index.html
Added some basic styling to give the callout boxes a more presentable,
mobile friendly appearance
Closes #30
=> Add styling to callout boxes

Gemfile, Gemfile.lock, config/skylight.yml
Added skylight to profile the app
Closes #37
=> Add skylight

coverage/.resultset.json, coverage/index.html
Forgot to push the keys up for skylight
=> Push skylight keys to heroku

config/skylight.yml, coverage/.resultset.json, coverage/index.html
Changed the Skylight ENV name to match the docs
=> Change Skylight ENV name

Gemfile, Gemfile.lock, app/serializers/state_serializer.rb, app/views/layouts/_nav.html.erb, app/views/states/index.html.erb, app/views/states/show.html.erb, config/environments/production.rb, coverage/.last_run.json, coverage/.resultset.json, coverage/index.html
Cached the views and added the memcachier heroku addon
=> Cache views

app/models/county.rb, app/models/state.rb, app/models/zipcode.rb, db/migrate/20160423211912_create_counties.rb, db/migrate/20160423211955_create_zipcodes.rb, db/schema.rb, lib/tasks/add_counties_and_zips_to_database.rake, schema.xml, spec/factories.rb, spec/models/county_spec.rb, spec/models/state_spec.rb, spec/models/zipcode_spec.rb
Add county and zipcode models and tables to database. 
Add rake tasks to seed database from csv and nrel database.
closes #49
=> 49 add zipcode install data to database

spec/models/county_spec.rb, spec/support/county_helper.rb
Add county helper to create county with installs
=> Add model test for county installs

app/assets/javascripts/charts/cost_by_year_chart.js, app/assets/javascripts/charts/installs_chart.js, app/assets/javascripts/charts/size_chart.js, app/assets/javascripts/find_device_width.js, app/assets/javascripts/loaders/state_loader.js, app/assets/javascripts/loaders/usa_loader.js, app/assets/stylesheets/main.scss, app/views/shared/_callout_boxes.html.erb, app/views/states/index.html.erb, app/views/states/show.html.erb
Used media queries to adjust the styling for desktop view
Closes #71
=> Add desktop styling

app/assets/javascripts/loaders/usa_loader.js
Forgot to change the URL's on the two JS files
=> Change URL back to heroku

app/assets/stylesheets/main.scss
Ran into some odd CSS that needed to be fixed for desktop and mobile
Closes #75
=> Fix styling

app/assets/stylesheets/main.scss
Ran into issues with iPad viewport, so had to change the margins to
percentages
Closes #75
=> Change graph margin to percentage

app/assets/javascripts/change_info_text.js, app/assets/javascripts/maps/load_state_map.js, app/assets/javascripts/maps/load_us_map.js
Took Adriene's suggestion and changed the infor text according to screen size
=> Adjust info text based of screen size

app/assets/javascripts/maps/load_state_map.js, app/assets/javascripts/maps/load_us_map.js
Fixed the zoom function on desktop and mobile
=> Fix zoom function
